export const jobData = [
  {
    company: "StitchFix",
    title: "Lead Product Designer",
    minSalary: 102800,
    maxSalary: 171000,
    type: "comparison",
    id: "stitchfix",
    link: "https://www.stitchfix.com/careers/jobs?gh_jid=7386505",
  },
  {
    company: "Moody's Corporation",
    title: "Experience Designer",
    minSalary: 107600,
    maxSalary: 156200,
    type: "comparison",
    id: "moodys",
    link: "https://www.linkedin.com/jobs/view/4323377889",
  },
  {
    company: "Omnidian",
    title: "Sr. UX Designer",
    minSalary: 110500,
    maxSalary: 149500,
    type: "comparison",
    id: "omnidian",
    link: "https://jobs.lever.co/omnidian/bf3b0bc1-2c6e-4059-bfa3-7e0c5a2bf5b9",
  },
  {
    company: "Hypergiant",
    title: "Senior UX/UI Designer",
    minSalary: 113000,
    maxSalary: 145000,
    type: "comparison",
    id: "hypergiant",
    link: "https://jobright.ai/jobs/info/690a385d4a1b456627b054a7",
  },
  {
    company: "Olo",
    title: "Senior Product Designer - Serve",
    minSalary: 114500,
    maxSalary: 156275.1,
    type: "comparison",
    id: "olo",
    link: "https://www.linkedin.com/jobs/view/4342387122",
  },
  {
    company: "Luna Physical Therapy",
    title: "Senior Product Designer",
    minSalary: 115000,
    maxSalary: 140000,
    type: "comparison",
    id: "luna",
    link: "https://www.linkedin.com/jobs/view/4338534379",
  },
  {
    company: "SelectQuote Insurance",
    title: "User Experience Designer III",
    minSalary: 115000,
    maxSalary: 130000,
    type: "comparison",
    id: "selectquote",
    link: "https://www.linkedin.com/jobs/view/4338807579",
  },
  {
    company: "Thumbtack",
    title: "Product Designer, Monetization Experience",
    minSalary: 127400,
    maxSalary: 164900,
    type: "comparison",
    id: "thumbtack",
    link: "https://careers.thumbtack.com/jobs/7423962",
  },
  {
    company: "Articulate",
    title: "Senior Product Designer I",
    minSalary: 129900,
    maxSalary: 194900,
    type: "comparison",
    id: "articulate",
    link: "https://jobs.lever.co/articulate/76a17f4d-8b38-4896-af16-ce3d7dc10df2",
  },
  {
    company: "Hammerspace",
    title: "UX Designer",
    minSalary: 130000,
    maxSalary: 170000,
    type: "comparison",
    id: "hammerspace",
    link: "https://ats.rippling.com/hammerspace/jobs/41e17d39-1f43-4503-9fba-5ab19ccb2191?utm_source=ziprecruiter",
  },
  {
    company: "ClassPass",
    title: "Senior Product Designer",
    minSalary: 140000,
    maxSalary: 175000,
    type: "comparison",
    id: "classpass",
    link: "https://www.playlist.com/careers/opportunities/4615177006",
  },
  {
    company: "Frontline Education",
    title: "Senior Product Designer",
    minSalary: 140000,
    maxSalary: 160000,
    type: "comparison",
    id: "frontline",
    link: "https://www.linkedin.com/jobs/view/4341883048",
  },
  {
    company: "Uplight",
    title: "Senior Product Designer",
    minSalary: 140000,
    maxSalary: 160000,
    type: "comparison",
    id: "uplight",
    link: "https://www.linkedin.com/jobs/view/4341275458",
  },
  {
    company: "FloQast",
    title: "Senior Product Designer",
    minSalary: 144000,
    maxSalary: 216000,
    type: "comparison",
    id: "floqast",
    link: "https://jobs.lever.co/floqast/5c2f43cc-0881-4196-989c-07b03495fd04",
  },
  {
    company: "Omada Health",
    title: "Senior Product Designer",
    minSalary: 149600,
    maxSalary: 187000,
    type: "comparison",
    id: "omada",
    link: "https://job-boards.greenhouse.io/omadahealth/jobs/7235667",
  },
  {
    company: "Signal Messenger",
    title: "Product Designer",
    minSalary: 150000,
    maxSalary: 210000,
    type: "comparison",
    id: "signal",
    link: "https://www.indeed.com/viewjob?jk=44fee9e03431b3b3&from=shareddesktop_copy",
  },
  {
    company: "Redox",
    title: "Senior Product Designer",
    minSalary: 156000,
    maxSalary: 184000,
    type: "comparison",
    id: "redox",
    link: "https://www.linkedin.com/jobs/view/4347366673",
  },
  {
    company: "Human Interest",
    title: "Senior Product Designer",
    minSalary: 175000,
    maxSalary: 200000,
    type: "comparison",
    id: "human",
    link: "https://job-boards.greenhouse.io/humaninterest/jobs/7391721?gh_src=dea5e79a1us",
  },
  {
    company: "Coinbase",
    title: "Sr. Product Designer - Pay Platform",
    minSalary: 180370,
    maxSalary: 212200,
    type: "comparison",
    id: "coinbase",
    link: "https://www.indeed.com/viewjob?jk=a331cf0b72031d3c&from=shareddesktop_copy",
  },
  {
    company: "Rula",
    title: "Sr. Product Designer (Remote) @ Rula",
    minSalary: 181000,
    maxSalary: 212900,
    type: "comparison",
    id: "rula",
    link: "https://jobs.ashbyhq.com/rula/2cba9b06-d875-4ed0-8d22-ea44840b81c8",
  },
  {
    company: "Sevaro",
    title: "Sr. UI/UX Designer - Healthcare",
    minSalary: 115000,
    maxSalary: 125000,
    type: "comparison",
    id: "sevaro",
    link: "https://www.indeed.com/viewjob?jk=4d817fe7c7b0c027&hl=en",
  },
  {
    company: "Vetcove",
    title: "Product Designer (Staff Level)",
    minSalary: 90000,
    maxSalary: 180000,
    type: "comparison",
    id: "vetcove",
    link: "https://www.indeed.com/viewjob?jk=a3edfba36cf6c0c8&hl=en",
  },
  {
    company: "Mindbody",
    title: "Senior Product Designer",
    minSalary: 140000,
    maxSalary: 175000,
    type: "comparison",
    id: "mindbody",
    link: "https://www.indeed.com/viewjob?jk=527e2cc806923325&hl=en",
  },
  {
    company: "Mural",
    title: "Senior Product Designer, Monetization",
    minSalary: 132000,
    maxSalary: 165000,
    type: "comparison",
    id: "mural",
    link: "https://www.indeed.com/viewjob?jk=527e2cc806923325&hl=en",
  },
  {
    company: "Humana",
    title: "Senior Product Designer",
    minSalary: 86300,
    maxSalary: 118700,
    type: "comparison",
    id: "humana",
    link: "https://www.indeed.com/viewjob?jk=ff7603c419b2f528&hl=en",
  },
  {
    company: "Variate",
    title: "Senior UX Designer",
    minSalary: 125000,
    maxSalary: 150000,
    type: "comparison",
    id: "variate",
    link: "https://www.linkedin.com/jobs/view/4334829873/?refId=e91f4597-8814-42ae-9761-43bf6f121bfd&trackingId=5QnToMurRNWsZC5IuTz8sA%3D%3D&trk=flagship3_job_home_savedjobs",
  },
  {
    company: "BLACKCLOAK",
    title: "Lead Product Designer",
    minSalary: 80000,
    maxSalary: 100000,
    type: "comparison",
    id: "blackcloak",
    link: "https://www.linkedin.com/jobs/view/4334865588",
  },
  {
    company: "Benchling",
    title: "Product Designer, Chemistry",
    minSalary: 153000,
    maxSalary: 230000,
    type: "comparison",
    id: "benchling",
    link: "https://www.linkedin.com/jobs/view/4313277706",
  },
  {
    company: "Atlassian",
    title: "Senior Product Designer",
    minSalary: 134100,
    maxSalary: 175075,
    type: "comparison",
    id: "atlassian",
    link: "https://www.atlassian.com/company/careers/details/23098",
  },
  {
    company: "Red Ventures",
    title: "Senior Product Designer | Coverage.com",
    minSalary: 100000,
    maxSalary: 187500,
    type: "comparison",
    id: "redventures",
    link: "https://www.indeed.com/viewjob?jk=5814839baff86f22&hl=en",
  },
  {
    company: "Position Under Review",
    title: "Sr. UI/UX Designer and Researcher",
    minSalary: 101000,
    maxSalary: 131000,
    type: "yourJob",
    id: "yourJob",
    link: "#",
  },
];

// Geographic zones for all three companies
export const companyGeographicZones = {
  Atlassian: {
    "Zone A": {
      color: "#dc2626",
      bgColor: "#fee2e2",
      description: "San Francisco Bay Area",
      cities: ["San Francisco Bay Area"],
    },
    "Zone B": {
      color: "#2563eb",
      bgColor: "#dbeafe",
      description: "High Cost Metro Areas",
      cities: [
        "Boston",
        "Los Angeles",
        "New York Tri-State Area",
        "Sacramento",
        "San Diego",
        "Seattle",
        "Washington D.C.",
      ],
    },
    "Zone C": {
      color: "#16a34a",
      bgColor: "#dcfce7",
      description:
        "All other states and metropolitan areas not mentioned above",
      cities: ["All other states and metropolitan areas not mentioned above"],
    },
  },
  "Snap Inc.": {
    "Zone A": {
      color: "#dc2626",
      bgColor: "#fee2e2",
      description: "California, Washington, New York City",
      cities: ["California", "Washington", "New York City"],
    },
    "Zone B": {
      color: "#2563eb",
      bgColor: "#dbeafe",
      description: "Select Major Cities",
      cities: ["Austin, TX", "Boulder, CO", "Washington DC", "Chicago, IL"],
    },
    "Zone C": {
      color: "#16a34a",
      bgColor: "#dcfce7",
      description: "All other states and metros not listed above",
      cities: ["All other states and metros not listed above"],
    },
  },
  Asana: {
    "Zone A": {
      color: "#dc2626",
      bgColor: "#fee2e2",
      description: "San Francisco Bay Area, NY/NJ/CT Metro Area",
      cities: [
        "San Francisco Bay Area, CA",
        "New York City, NY",
        "Long Island, NY",
        "Newark, NJ",
        "Stamford, CT",
      ],
    },
    "Zone B": {
      color: "#2563eb",
      bgColor: "#dbeafe",
      description: "Major Metro Areas",
      cities: [
        "Connecticut (non-NYC Area)",
        "New Jersey (non-NYC Area)",
        "Albany, NY",
        "Boston, MA",
        "Chicago, IL",
        "Denver, CO",
        "Los Angeles, CA",
        "Miami, FL",
        "Portland, OR",
        "Sacramento, CA",
        "San Diego, CA",
        "Seattle, WA",
        "Washington, D.C.",
      ],
    },
    "Zone C": {
      color: "#16a34a",
      bgColor: "#dcfce7",
      description: "All other states and metros not listed above",
      cities: ["All other states and metros not listed above"],
    },
  },
};

// City coordinates for all companies
export const companyCityCoordinates = {
  Atlassian: [
    // Zone A - San Francisco Bay Area
    {
      name: "San Francisco",
      coordinates: [-122.4194, 37.7749],
      zone: "Zone A",
    },
    { name: "San Jose", coordinates: [-121.8863, 37.3382], zone: "Zone A" },
    { name: "Oakland", coordinates: [-122.2711, 37.8044], zone: "Zone A" },
    { name: "Palo Alto", coordinates: [-122.143, 37.4419], zone: "Zone A" },
    {
      name: "Mountain View",
      coordinates: [-122.0838, 37.3861],
      zone: "Zone A",
    },

    // Zone B Cities
    { name: "Boston", coordinates: [-71.0589, 42.3601], zone: "Zone B" },
    { name: "Los Angeles", coordinates: [-118.2437, 34.0522], zone: "Zone B" },
    { name: "New York", coordinates: [-74.006, 40.7128], zone: "Zone B" },
    { name: "Sacramento", coordinates: [-121.4944, 38.5816], zone: "Zone B" },
    { name: "San Diego", coordinates: [-117.1611, 32.7157], zone: "Zone B" },
    { name: "Seattle", coordinates: [-122.3321, 47.6062], zone: "Zone B" },
    { name: "Washington DC", coordinates: [-77.0369, 38.9072], zone: "Zone B" },
  ],
  "Snap Inc.": [
    // Zone A
    {
      name: "California",
      coordinates: [-119.4179, 36.7783],
      zone: "Zone A",
      isState: true,
    },
    {
      name: "Washington",
      coordinates: [-120.7401, 47.7511],
      zone: "Zone A",
      isState: true,
    },
    { name: "New York", coordinates: [-74.006, 40.7128], zone: "Zone A" },

    // Zone B
    { name: "Austin", coordinates: [-97.7431, 30.2672], zone: "Zone B" },
    { name: "Boulder", coordinates: [-105.2705, 40.015], zone: "Zone B" },
    { name: "Washington DC", coordinates: [-77.0369, 38.9072], zone: "Zone B" },
    { name: "Chicago", coordinates: [-87.6298, 41.8781], zone: "Zone B" },
  ],
  Asana: [
    // Zone A
    {
      name: "San Francisco",
      coordinates: [-122.4194, 37.7749],
      zone: "Zone A",
    },
    { name: "San Jose", coordinates: [-121.8863, 37.3382], zone: "Zone A" },
    { name: "Oakland", coordinates: [-122.2711, 37.8044], zone: "Zone A" },
    { name: "New York", coordinates: [-74.006, 40.7128], zone: "Zone A" },
    { name: "Long Island", coordinates: [-73.102, 40.83], zone: "Zone A" },
    { name: "Newark", coordinates: [-74.1724, 40.7357], zone: "Zone A" },
    { name: "Stamford", coordinates: [-73.5387, 41.0534], zone: "Zone A" },

    // Zone B
    { name: "Albany", coordinates: [-73.7562, 42.6526], zone: "Zone B" },
    { name: "Boston", coordinates: [-71.0589, 42.3601], zone: "Zone B" },
    { name: "Chicago", coordinates: [-87.6298, 41.8781], zone: "Zone B" },
    { name: "Denver", coordinates: [-104.9903, 39.7392], zone: "Zone B" },
    { name: "Los Angeles", coordinates: [-118.2437, 34.0522], zone: "Zone B" },
    { name: "Miami", coordinates: [-80.1918, 25.7617], zone: "Zone B" },
    { name: "Portland", coordinates: [-122.6784, 45.5152], zone: "Zone B" },
    { name: "Sacramento", coordinates: [-121.4944, 38.5816], zone: "Zone B" },
    { name: "San Diego", coordinates: [-117.1611, 32.7157], zone: "Zone B" },
    { name: "Seattle", coordinates: [-122.3321, 47.6062], zone: "Zone B" },
    { name: "Washington DC", coordinates: [-77.0369, 38.9072], zone: "Zone B" },
  ],
};
